# SPDX-FileCopyrightText: 2020-2025 CERN.
# SPDX-FileCopyrightText: 2022-2026 Graz University of Technology.
# SPDX-FileCopyrightText: 2026 TU Wien.
# SPDX-License-Identifier: MIT

[project]
name = "marshmallow-utils"
description = "Extras and utilities for Marshmallow."
readme = "README.rst"
requires-python = ">=3.8"
license = "MIT"
authors = [
  { name = "CERN", email = "info@inveniosoftware.org" },
]
keywords = [
  "invenio",
  "search",
  "ui",
]
classifiers = [
  "Development Status :: 5 - Production/Stable",
]
dependencies = [
  "babel>=2.8",
  "babel-edtf>=1.2.0",
  "bleach[css]>=5.0.0",
  "edtf>=5.0.0,<6.0.0",
  "ftfy>=4.4.3",
  "geojson>=2.5.0",
  "idutils>=1.1.8",
  "marshmallow>=3.5.0,<4.0.0",
  "marshmallow-oneofschema>=2.1.0",
  "pendulum>=3.0.0",
  "pycountry>=18.12.8",
  "uritemplate>=3.0.1",
  "werkzeug>=1.0.0",
]
dynamic = ["version"]

[project.urls]
Repository = "https://github.com/inveniosoftware/marshmallow-utils"

[project.entry-points."invenio_i18n.translations"]
marshmallow_utils = "marshmallow_utils"

[project.optional-dependencies]
tests = [
  "coverage>=5.2.1",
  "pytest-black>=0.6.0",
  "pytest-cov>=2.10.1",
  "pytest-isort>=1.2.0",
  "pytest-pydocstyle>=2.2.0",
  "pytest>=6.0,<9.0.0",
  "sphinx>=4.2.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

# see https://babel.pocoo.org/en/latest/messages.html#toml-configuration-format
[tool.babel]
[tool.babel.compile_catalog]
directory = "marshmallow_utils/translations/"
use_fuzzy = true

[tool.babel.extract_messages]
copyright_holder = "CERN"
msgid_bugs_address = "info@inveniosoftware.org"
mapping_file = "pyproject.toml"
output_file = "marshmallow_utils/translations/messages.pot"
add_comments = "NOTE"

[tool.babel.init_catalog]
input_file = "marshmallow_utils/translations/messages.pot"
output_dir = "marshmallow_utils/translations/"

[[tool.babel.mappings]]
method = "javascript"
pattern = "**.js"
encoding = "utf-8"
extract_messages = "$._, jQuery._"

[[tool.babel.mappings]]
method = "python"
pattern = "**.py"
encoding = "utf-8"

[[tool.babel.mappings]]
method = "jinja2"
pattern = "**/templates/**.html"
encoding = "utf-8"

[tool.hatch.version]
path = "marshmallow_utils/__init__.py"

[tool.hatch.build]
artifacts = [
  "*.mo",
]

[tool.hatch.build.targets.sdist]
include = [
  "/marshmallow_utils",
]

[tool.isort]
profile = "black"

[tool.pydocstyle]
add_ignore = "D401"

[tool.pytest.ini_options]
addopts = '--black --isort --pydocstyle --doctest-glob="*.rst" --doctest-modules --cov=marshmallow_utils --cov-report=term-missing'
filterwarnings = ["ignore::pytest.PytestDeprecationWarning"]
testpaths = "tests marshmallow_utils"
live_server_scope = "module"
